# Generated by Django 3.2.16 on 2022-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.SmallIntegerField(default=0),
        ),
    ]
