# Generated by Django 3.2.16 on 2022-12-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.SmallIntegerField(default=0, verbose_name='edad'),
        ),
    ]
